In [2]:
import numpy as np

In [3]:
a1 = np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [4]:
a1.shape

(5,)

In [5]:
a1.ndim

1

# 

In [6]:
type(a1)

numpy.ndarray

In [7]:
a1.size

5

In [10]:
a2 = np.array([[1,2.1,3],
            [2,3,4.3]])

In [12]:
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.1  3.0
1  2.0  3.0  4.3

In [15]:
zeroes = np.zeros((2,3))
zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
range_arr = np.arange(0,10,2)
range_arr

array([0, 2, 4, 6, 8])

In [22]:
rand = np.random.randint(0,3, size = (2,4))
rand

array([[2, 1, 2, 1],
       [2, 2, 0, 0]])

In [24]:
random = np.random.random((5,3))
random

array([[0.02069526, 0.82851316, 0.99724532],
       [0.34418674, 0.96182527, 0.91802362],
       [0.76188072, 0.04631668, 0.06328977],
       [0.02537018, 0.03342418, 0.21551721],
       [0.73709693, 0.54620062, 0.10221931]])

In [4]:
a4 = np.random.randint(10, size = (2,3,4,5))
a4

array([[[[3, 3, 5, 6, 8],
         [8, 3, 1, 9, 1],
         [0, 6, 7, 7, 4],
         [3, 4, 4, 9, 0]],

        [[0, 5, 5, 0, 5],
         [5, 8, 8, 7, 7],
         [3, 5, 6, 7, 1],
         [0, 6, 7, 7, 1]],

        [[2, 6, 2, 8, 6],
         [3, 9, 0, 4, 6],
         [4, 7, 6, 1, 5],
         [8, 7, 4, 6, 6]]],


       [[[9, 0, 3, 5, 9],
         [3, 0, 9, 7, 2],
         [0, 6, 4, 9, 5],
         [3, 0, 9, 6, 1]],

        [[3, 9, 9, 1, 0],
         [8, 3, 1, 0, 8],
         [5, 2, 7, 3, 0],
         [9, 9, 6, 0, 7]],

        [[1, 7, 0, 2, 7],
         [1, 9, 3, 4, 6],
         [4, 9, 4, 2, 9],
         [1, 5, 6, 4, 4]]]])

In [9]:
a4[:,:,:,:2]

array([[[[3, 3],
         [8, 3],
         [0, 6],
         [3, 4]],

        [[0, 5],
         [5, 8],
         [3, 5],
         [0, 6]],

        [[2, 6],
         [3, 9],
         [4, 7],
         [8, 7]]],


       [[[9, 0],
         [3, 0],
         [0, 6],
         [3, 0]],

        [[3, 9],
         [8, 3],
         [5, 2],
         [9, 9]],

        [[1, 7],
         [1, 9],
         [4, 9],
         [1, 5]]]])